/*
 * Generated by MTK DrvGen Version 5.09.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Sat Jun 15 22:29:03 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


