#!/usr/local/bin/perl

ifeq ($(MTK_EMMC_SUPPORT),yes)
BOARD_SECROIMAGE_PARTITION_SIZE:=5M
BOARD_SYSTEMIMAGE_PARTITION_SIZE:=383M
BOARD_CACHEIMAGE_PARTITION_SIZE:=255M
BOARD_USERDATAIMAGE_PARTITION_SIZE:=510M
endif 
